# 情境 : 根據 branch name 部屬 Docker 服務到不同的 host 上.

variables:
  # When using dind service, you must instruct docker to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  DOCKER_HOST: tcp://docker:2375

  # Docker-in-Docker with TLS disabled in the Docker executor
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""

  # To enable debug logging (tracing), set the CI_DEBUG_TRACE variable to 'true'
  # CI_DEBUG_TRACE: "true"

  # 並不是所有 job 都需要 clone source code. (https://docs.gitlab.com/ee/ci/runners/configure_runners.html#git-strategy)
  GIT_STRATEGY: none

  # 可以定義成 Global variable
  IMAGE_REGISTRY_HOSTED: "sfcs-docker.mic.com.tw:8091"
  IMAGE_REGISTRY_GROUP: "sfcs-docker.mic.com.tw:8090"

  CV_APP_NAME: "flow-module"
  CV_ENVIRONMENT: $CI_COMMIT_REF_SLUG
  CV_TAG: "None"
  CV_IMAGE_NAME: ${CV_APP_NAME}-${CV_ENVIRONMENT}
  CV_DEPLOY_HOST: "10.88.26.161"

# 執行條件:
# 必須要存在 Dockerfile, gitlab-ci-variables.yml
# 必須要更改 gitlab-ci-variables.yml 中的 tag
# Conditional Set Variable
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
        - gitlab-ci-variables.yml
      changes:
        - gitlab-ci-variables.yml
    - if: $CI_COMMIT_REF_SLUG == "main"
      variables:
        CV_ENVIRONMENT: "prod"
        # 切換成正式區的 host ip
        CV_DEPLOY_HOST: "10.88.26.237"

default:
  tags: # 如果使用了多個 tags 那 gitlab runner 必須都具有這些 tags 才會將 job 指派給它.
    - docker # 預設每個 job 都使用 docker executor 執行 (gitlab runner 註冊時 tag 須加上 docker).

stages: # DevSecOps 的stages, 也代表 job 的執行順序.
  - info
  - variables
  - build-scan
  - publish
  - deploy

.show-info:
  stage: info
  script:
    - echo "顯示所有 GitLab 變數."
    - export
  after_script:
    - echo "show-info."

# 使用 yq - YAML Processor 來解析 gitlab-ci-variables.yml 中的變數.
# 並透過 artifacts.reports.dotenv 傳遞變數讓相依的 job 取用.
assign-variables:
  stage: variables
  variables:
    GIT_STRATEGY: fetch # equal to git clean + git fetch
  before_script:
    - "wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64"
    - "chmod a+x /usr/local/bin/yq"
    - "yq --version"
    - CV_TAG=$(yq -e '.variables.tag' gitlab-ci-variables.yml)
  script:
    - echo "Assign variable..."
    - echo "${CV_ENVIRONMENT} ${CV_TAG}"
    - echo "CV_ENVIRONMENT=${CV_ENVIRONMENT}" >> variables.env
    - echo "CV_TAG=${CV_TAG}" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

# 將原先 SonarQube 產生的 script 整合至 Dockerfile 中, 再透過 docker build 動態把參數傳入.
build-dockerfile:
  stage: build-scan
  variables:
    GIT_STRATEGY: fetch # equal to git clean + git fetch
  dependencies:
    - assign-variables
  script:
    - echo "Build docker image and SonarScanner check..."
    - echo "$CV_ENVIRONMENT $CV_TAG"
    - >
      docker build
      -f WebApi.Module.Flow/Dockerfile
      --build-arg env=${CV_ENVIRONMENT}
      --build-arg version=${CV_TAG}
      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
      --label "org.opencontainers.image.url=$CI_PROJECT_URL"
      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
      -t ${CV_IMAGE_NAME}:${CV_TAG} --no-cache .
    - docker save -o ${CV_IMAGE_NAME}:${CV_TAG}.tgz ${CV_IMAGE_NAME}:${CV_TAG}
  artifacts:
    name: "$CI_JOB_NAME-artifacts"
    paths: # 將 docker save 匯出的 image 保存起來
      - ${CV_IMAGE_NAME}:${CV_TAG}.tgz
    expire_in: 30 mins # artifacts 的檔案只保存 30 分鐘

# 此段語法可直接從 SonarQube 產生
# sonarqube-check:
#   stage: scan
#   image: mcr.microsoft.com/dotnet/sdk:5.0 # 必須修改為 sdk 映像檔
#   variables:
#     SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
#     GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis task
#   cache:
#     key: "${CI_JOB_NAME}"
#     paths:
#       - .sonar/cache
#   script:
#     - echo "Scan image..."
#     - "apt-get update"
#     - "apt-get install --yes openjdk-11-jre"
#     - "dotnet tool install --global dotnet-sonarscanner"
#     - 'export PATH="$PATH:$HOME/.dotnet/tools"'
#     - 'dotnet sonarscanner begin /k:"demo" /v:"$CI_COMMIT_SHORT_SHA" /d:sonar.login="$SONAR_TOKEN" /d:"sonar.host.url=$SONAR_HOST_URL" /d:sonar.qualitygate.wait="true" '
#     - "dotnet build"
#     - 'dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"'
#   #allow_failure: true
#   only:
#     - DEV # DEV branch 才執行 scan stage

# 只有前面的 stage 都成功執行後才會執行 publish stage.
publish-to-nexus:
  variables:
    GIT_STRATEGY: none
  stage: publish
  dependencies:
    - assign-variables
    - build-dockerfile
  before_script:
    - mkdir -p $HOME/.docker
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  script: # 讀取從 build-dockerfile job 保存的 image 然後發布至 Nexus docker registry
    - echo "Publish to Nexus server..."
    - docker load -i ${CV_IMAGE_NAME}:${CV_TAG}.tgz
    - docker tag ${CV_IMAGE_NAME}:${CV_TAG} ${IMAGE_REGISTRY_HOSTED}/${CV_IMAGE_NAME}:${CV_TAG}
    - docker push ${IMAGE_REGISTRY_HOSTED}/${CV_IMAGE_NAME}:${CV_TAG}

deploy-service:
  variables: # overwrite global DOCKER_HOST value
    DOCKER_HOST: ""
  stage: deploy
  tags:
    - shell # 使用 Shell Executor
    - ${CV_DEPLOY_HOST}
  dependencies:
    - assign-variables
  before_script:
    # 必須做 login 的動作, 做身分驗證 (本以為會直接讀取 ~/.docker/config.json 卻沒生效...)
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD ${IMAGE_REGISTRY_GROUP}
  script: # 從 Nexus docker registry 下載先前發布的 image, 並且運行起來.
    - echo "Deploy to ${CV_DEPLOY_HOST} ..."
    - docker pull ${IMAGE_REGISTRY_GROUP}/${CV_IMAGE_NAME}:${CV_TAG}
    - |
      if [[ $(docker inspect -f '{{.State.Running}}' $CV_IMAGE_NAME) == "true" ]]; then
        echo "Stop $CV_IMAGE_NAME first..."
        docker container stop $CV_IMAGE_NAME
        docker container rm $CV_IMAGE_NAME
      else
        echo "$CV_IMAGE_NAME not running"
      fi
    - docker run -d -p 7770:80 --name $CV_IMAGE_NAME ${IMAGE_REGISTRY_GROUP}/${CV_IMAGE_NAME}:${CV_TAG}
