concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker@238"
  url = "http://10.88.26.237:80"
  token = "m8r57KUTMyjztJYHZZde"
  executor = "docker"
  environment = ["DOCKER_AUTH_CONFIG={\"auths\":{\"sfcs-docker.mic.com.tw:8083\":{\"auth\":\"c2Zjcy50ZXN0ZXI6c2Zjcw==\"},\"sfcs-docker.mic.com.tw:8091\":{\"auth\":\"c2Zjcy50ZXN0ZXI6c2Zjcw==\"}}}"]
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:20.10.13"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    [[runners.docker.services]]
      name = "docker:20.10.13-dind"